return {
  -- 'rmagatti/auto-session',
  -- config = function()
  --   local auto_session = require 'auto-session'
  --
  --   vim.o.sessionoptions = 'blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions'
  --
  --   auto_session.setup {
  --     auto_restore_enabled = true,
  --     auto_session_suppress_dirs = { '~/', '~/Dev/', '~/Downloads', '~/Documents', '~/Desktop/' },
  --     log_level = 'info', -- Optional: Set logging level to help with debugging
  --     -- Specify a custom session directory if needed
  --     auto_session_dir = os.getenv 'HOME' .. '/.local/share/nvim/sessions/',
  --   }
  --
  --   local keymap = vim.keymap
  --
  --   keymap.set('n', '<leader>sr', '<cmd>SessionRestore<CR>', { desc = 'Restore session for cwd' }) -- restore last workspace session for current directory
  --   keymap.set('n', '<leader>ss', '<cmd>SessionSave<CR>', { desc = 'Save session for auto session root dir' }) -- save workspace session for current working directory
  -- end,
}
